name: Test Workflow

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '.github/workflows/**'

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install cscope
      run: sudo apt-get update && sudo apt-get install -y cscope

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --dev

    - name: Test basic functionality
      run: |
        echo "Testing basic setup..."
        uv run python -c "import lock_trace; print('lock_trace module imported successfully')"
        uv run python -c "from lock_trace.cli import main; print('main function imported successfully')"
        echo "Basic tests passed!"